### ISSUE TITLE
Always on top feature doesn't seem to work

### ISSUE THREAD

**Issue by pratapvardhan** [sanand0/onething#1]
`Always on top` feature doesn't to work. I've tried from apps launch and ran via cmd.

The moment you move to another window, it minimizes itself or I might have misunderstood the way it is supposed to work!

**Comment by sanand0** [comment]
Same here. I am using AutoHotKey instead to keep it always on top. No idea how to resolve this yet.

**Comment by pratapvardhan** [comment]
Above PR works fine between switching applications. But the catch -- actions like `Win + D` will minimize all applications including onething.

**Comment by sanand0** [comment]
Support we want to disable always-on-top temporarily, what shortcut key would be appropriate? Ctrl-T perhaps?

**Comment by pratapvardhan** [comment]
How does this short-key work? Only when it on `always-on-top` mode or when on minimized mode too, like a toggle feature?

So, essentially it can be shortcut key for minimizing the window itself?
